name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r Algoritmogenetico/requirements.txt

    - name: Run tests
      run: |
        pytest Algoritmogenetico/tests --maxfail=1 --disable-warnings

  deploy:
    needs: test  # Il job di deploy si avvia solo se il test job ha successo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > ssh_key
        chmod 600 ssh_key
        rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" Algoritmogenetico/ user@server:/path/to/deployment/
        ssh -i ssh_key -o StrictHostKeyChecking=no user@server "cd /path/to/deployment && pip install -r requirements.txt && systemctl restart myapp"

    - name: Clean up
      run: rm ssh_key
